### ISSUE TITLE
panic: router only implemented in linux

### ISSUE THREAD

**Issue by sxueck** [liamg/furious#5]
Does not support windows

`furious 192.168.218.149`

```Starting scan at 2019-09-01 23:57:00.0992542 +08
00 CST m=+0.031451601

panic: router only implemented in linux

goroutine 26 [running]:
github.com/liamg/furious/vendor/github.com/googl
e/gopacket/routing.New(...)
        C:/Users/sxuec/go/src/github.com/liamg/f
urious/vendor/github.com/google/gopacket/routing
/other.go:14
github.com/liamg/furious/scan.(*SynScanner).scan
Host(0xc00005eba0, 0xc000056a40, 0x10, 0x10, 0xc
000268000, 0x16b4, 0x1c00, 0xc000041740, 0xc0000
41860, 0x7b5580, ...)
        C:/Users/sxuec/go/src/github.com/liamg/f
urious/scan/scan-syn.go:242 +0x2b2
github.com/liamg/furious/scan.(*SynScanner).Star
t.func1(0xc00005eba0)
        C:/Users/sxuec/go/src/github.com/liamg/f
urious/scan/scan-syn.go:74 +0x17a
created by github.com/liamg/furious/scan.(*SynSc
anner).Start
        C:/Users/sxuec/go/src/github.com/liamg/f
urious/scan/scan-syn.go:68 +0x4a```

**Comment by sxueck** [comment]
I understand
`handle.WritePacketData()` can only be used for linux

**Comment by neurolimitless** [comment]
Then I guess the code should be updated as it doesn't work on mac either. Why did you close the issue?
